#!/bin/bash

function split_gif() {
    ANIMATED=$1
    convert ../$ANIMATED -scene 1 +adjoin frame_%04d.gif
}

function scale_down() {
    FRAME=$1
    convert $FRAME -resize 10x10 -trim +repage TRIMMED_$FRAME
}

function get_rgb_at() {
    FRAME=$1
    X_POS=$2
    Y_POS=$3

    convert $FRAME -format "%[fx:int(255*r)],%[fx:int(255*g)],%[fx:int(255*b)]" info:
}

function get_rgb_for() {
    
    FRAME=$1
    convert $FRAME txt:- | \
        xargs -L1 echo | \
        sed -e 's,#.*$,,'
}

function get_image_dimensions() {

    F=tmp/TRIMMED_frame_0001.gif
    IMG_DIMENSIONS=$(identify -verbose $F | \
        grep Geometry | \
        cut -d':' -f2 | \
        cut -d'+' -f1 | \
        sed -e 's, ,,g')
    echo ${IMG_DIMENSIONS}
}
function get_image_width() {
    IMG_X=$(get_image_dimensions | \
        cut -d'x' -f1)
    echo ${IMG_X}
}

function get_image_height() {
    IMG_Y=$(get_image_dimensions | \
        cut -d'x' -f2)
    echo ${IMG_Y}
}
